dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-11/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: RsPPesYCu1gmeeANeswYoTsgaSCksAdBucW80L0kDj15bkEkYHaupp3fb2e1Y7o7z+RNDihnvcxoxxLxYoui4by84zyAG35fO+3fzan46heDSjZH5OL29IZwTYAqHqFXrD6G3tkyMQku4Q0sRu8jSjDq3VbC72ud9aV6X60w4IODilU+lcnQCnYSJkb9e+vezOfqkWgoivinxNHQBmDrWdtKiIUY6frw+q3jBrr6VPqW3FB5JospJ0uMPaELlEFxzo4MnqLnder5fmaAMHduj5iEPmYJknqzXQYa0zpVAgBtyOOBxl4LwtLlpLDjPHfheg3DJsQ/xkrVv66Uj/93dn7PerVXpBzDWcSpfHMCF0D2x3JK9aUuZnezrE+HnGSHN2QbVc/xKeb848f49ZayIwbr2t3hLvsv30aKxwQik4T07ov4vPjJZl08/HKnhtewe1U0MGkjeXI5gYwkVvE9oXQH5NAJeJvKZHbrH/0+yt1t7CK8hiShQoUYfe9JAlYklNJuGIMGl+NWKIeUOGeotRPAWC8840ztEUqVcZPbxRhjGcQwjzz5aUYZ6CAFURk3zenjsVQxyppjAhBu5kSRPXrQA+wenZ6XSXl6EquxuEtA46B5DQYFh75rN8CdbQh+3ktCgoILkpnnKvz94bSBmwbzSJ8pmn3RAiaKZ4ueRAE=
